### ISSUE TITLE
Support creating a BGP-enabled project

### ISSUE THREAD

**Issue by ctreatma** [equinix-labs/metal-project-action#14]
A test workflow that I ran to validate our `metal-go`-based actions failed in part because the project created by the project action does not have BGP enabled: https://github.com/equinix-labs/terraform-equinix-kubernetes-cluster/actions/runs/5271262073/jobs/9532079416

It's possible it would be better to fix this by adding a terraform resource that can enable/configure BGP on an existing project, but we could potentially update this action to accept optional BGP configuration settings and to enable BGP for the project if those settings are provided.

**Comment by displague** [comment]
Related terraform resource issue is: https://github.com/equinix/terraform-provider-equinix/issues/160

Regardless of TF support, I see benefit in adding this feature to metal-project-action which can be used independent of Terraform use-cases.

**Comment by displague** [comment]
Fixed in #36
